import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,team,analytics }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1>rootLayout</h1>
      {children}
      {team}
      {analytics}
      </body>
    </html>
  );
}

