global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

#业务监控
  - job_name: 'springboot'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.5.120:8080']
rule_files:
  - /prometheus/rules/business-alert.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['host.docker.internal:9093']